spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_me_soft?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: thepassword
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8081/auth/realms/testmesoft/protocol/openid-connect/certs}